### PR TITLE
PIPE2D-1149: Make fitPfsFluxReference & fitFluxCal compatible with Gen3 butler

### PR DESCRIPTION
**Pull request by SogoMineo**
Added the elements necessary for `FitPfsFluxReferenceTask` and `FitFluxCalTask` to be compatible with Gen3 butler.

### CODE REVIEW

**Review by PaulPrice — APPROVED** [review]
Is it worth inheriting from the prototype flux calibration task instead of duplicating everything?

**Comment by SogoMineo** [comment]
I think `*Connection` classes can inherit from, or be replaced by, the prototype one. However, I don't want `FitFluxCalTask` to directly inherit from `FluxCalibrateTask`, for some member functions have different parameters. If I am allowed to rewrite the prototype `FluxCalibrateTask` so that it will inherit from a base class, I can let `FitFluxCalTask` inherit from the same base class, too.

**Comment by PaulPrice** [comment]
That's a good idea.

**Comment by SogoMineo** [comment]
I tried to extract common parts of `FluxCalibrateTask` and `FitFluxCalTask`, and I found that their `run()` methods have different signatures from each other. `FluxCalibrateTask.run()` takes `Dict[int, PfsReference]` whereas `FitFluxCalTask.run()` takes `PfsFluxReference`. The former `run()` cannot adjust itself to the latter because of Gen2 interface. I don't think it worth to make a common base class that does not even have `run()`.

**Comment by SogoMineo** [comment]
I delete `FitFluxCalConnections` and use `FluxCalibrateConnections` instead. I think this is reasonable because the input and output of `FitFluxCalTask` are the same as those of `FluxCalibrateConnections` in gen3.

**Comment by SogoMineo** [comment]
Can I merge the current branch, or should I work on deleting more common lines?

**Comment by PaulPrice** [comment]
Please go ahead an merge. Thanks!

**Pull request merged**
